# -*- coding: utf-8 -*-
"""translate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wgqo3dbDbsiCWhIsnvp06vnl6Ac9qW6Z
"""

from easynmt import EasyNMT
model = EasyNMT('opus-mt')

def get_translate(sentence):
      return model.translate(sentence, target_lang='en', max_new_tokens=500) #翻訳後文章

text = '''APIの勉強のために, Twitter apiを用いてユーザのツイート取得を行ったので, 簡単に流れをまとめました.以下が内容です.1. Twitter developerでのAPI申請2. APIを用いてのツイート取得をcurlコマンドで行う'''
text_translated=get_translate(text)
print(text_translated)  #Hello, it's good weather today!